// <auto-generated />
using System;
using DogisAnaliz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DogisAnaliz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913153352_AddStandingsTeamStatsPredictions")]
    partial class AddStandingsTeamStatsPredictions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DogisAnaliz.Models.DogiPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertMatchId")
                        .HasColumnType("integer");

                    b.Property<string>("AlertResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerMatch1Id")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerMatch2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertMatchId");

                    b.HasIndex("AlertResult");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TriggerMatch2Id");

                    b.HasIndex("TriggerMatch1Id", "TriggerMatch2Id", "TeamId")
                        .IsUnique();

                    b.ToTable("DogiPatterns");
                });

            modelBuilder.Entity("DogisAnaliz.Models.FixturePrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Advice")
                        .HasColumnType("text");

                    b.Property<int>("ApiFixtureId")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("GoalsAway")
                        .HasColumnType("text");

                    b.Property<string>("GoalsHome")
                        .HasColumnType("text");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<double>("PercentAway")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentDraw")
                        .HasColumnType("double precision");

                    b.Property<double>("PercentHome")
                        .HasColumnType("double precision");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("UnderOver")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WinOrDraw")
                        .HasColumnType("boolean");

                    b.Property<string>("WinnerComment")
                        .HasColumnType("text");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiFixtureId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.ToTable("FixturePredictions");
                });

            modelBuilder.Entity("DogisAnaliz.Models.FixtureSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiFixtureId")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KickoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiFixtureId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("KickoffUtc");

                    b.HasIndex("SeasonId");

                    b.HasIndex("LeagueId", "SeasonId", "Week");

                    b.ToTable("FixtureSchedules");
                });

            modelBuilder.Entity("DogisAnaliz.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("FtAwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("FtHomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("HtAwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("HtHomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DogisAnaliz.Models.MatchDetail", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("AdditionalDataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Referee")
                        .HasColumnType("text");

                    b.HasKey("MatchId");

                    b.ToTable("MatchDetails");
                });

            modelBuilder.Entity("DogisAnaliz.Models.MatchSurprise", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDoubleSurprise")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHighGoal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTurnaround")
                        .HasColumnType("boolean");

                    b.Property<string>("IyMsCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SurpriseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalGoals")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.HasIndex("IsHighGoal");

                    b.HasIndex("IsTurnaround");

                    b.HasIndex("SurpriseType");

                    b.ToTable("MatchSurprises");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayDraw")
                        .HasColumnType("integer");

                    b.Property<int>("AwayGoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("AwayGoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("AwayLose")
                        .HasColumnType("integer");

                    b.Property<int>("AwayPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("AwayWin")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Draw")
                        .HasColumnType("integer");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("HomeDraw")
                        .HasColumnType("integer");

                    b.Property<int>("HomeGoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("HomeGoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("HomeLose")
                        .HasColumnType("integer");

                    b.Property<int>("HomePlayed")
                        .HasColumnType("integer");

                    b.Property<int>("HomeWin")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("Lose")
                        .HasColumnType("integer");

                    b.Property<int>("Played")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Win")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DogisAnaliz.Models.TeamSeasonStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardsRedTotal")
                        .HasColumnType("integer");

                    b.Property<int>("CardsYellowTotal")
                        .HasColumnType("integer");

                    b.Property<int>("CleanSheetsAway")
                        .HasColumnType("integer");

                    b.Property<int>("CleanSheetsHome")
                        .HasColumnType("integer");

                    b.Property<int>("CleanSheetsTotal")
                        .HasColumnType("integer");

                    b.Property<int>("FailedToScoreAway")
                        .HasColumnType("integer");

                    b.Property<int>("FailedToScoreHome")
                        .HasColumnType("integer");

                    b.Property<int>("FailedToScoreTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GoalsAgainstAvgAway")
                        .HasColumnType("double precision");

                    b.Property<double>("GoalsAgainstAvgHome")
                        .HasColumnType("double precision");

                    b.Property<double>("GoalsAgainstAvgTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("GoalsForAvgAway")
                        .HasColumnType("double precision");

                    b.Property<double>("GoalsForAvgHome")
                        .HasColumnType("double precision");

                    b.Property<double>("GoalsForAvgTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMissed")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyScored")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "SeasonId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamSeasonStats");
                });

            modelBuilder.Entity("DogisAnaliz.Models.DogiPattern", b =>
                {
                    b.HasOne("DogisAnaliz.Models.Match", "AlertMatch")
                        .WithMany()
                        .HasForeignKey("AlertMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DogisAnaliz.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Match", "TriggerMatch1")
                        .WithMany()
                        .HasForeignKey("TriggerMatch1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Match", "TriggerMatch2")
                        .WithMany()
                        .HasForeignKey("TriggerMatch2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlertMatch");

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("Team");

                    b.Navigation("TriggerMatch1");

                    b.Navigation("TriggerMatch2");
                });

            modelBuilder.Entity("DogisAnaliz.Models.FixturePrediction", b =>
                {
                    b.HasOne("DogisAnaliz.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DogisAnaliz.Models.FixtureSchedule", b =>
                {
                    b.HasOne("DogisAnaliz.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Match", b =>
                {
                    b.HasOne("DogisAnaliz.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("DogisAnaliz.Models.MatchDetail", b =>
                {
                    b.HasOne("DogisAnaliz.Models.Match", "Match")
                        .WithOne("Detail")
                        .HasForeignKey("DogisAnaliz.Models.MatchDetail", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("DogisAnaliz.Models.MatchSurprise", b =>
                {
                    b.HasOne("DogisAnaliz.Models.Match", "Match")
                        .WithOne("Surprise")
                        .HasForeignKey("DogisAnaliz.Models.MatchSurprise", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Standing", b =>
                {
                    b.HasOne("DogisAnaliz.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DogisAnaliz.Models.TeamSeasonStat", b =>
                {
                    b.HasOne("DogisAnaliz.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DogisAnaliz.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Season");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DogisAnaliz.Models.League", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Match", b =>
                {
                    b.Navigation("Detail");

                    b.Navigation("Surprise");
                });

            modelBuilder.Entity("DogisAnaliz.Models.Season", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
